"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      data-theme={localStorage.getItem("theme") || "light"}
      lang="en">
      <body className={inter.className}>
        <Navbar />
        <main className="m-5">{children}</main>
      </body>
    </html>
  );
}
